### ISSUE TITLE
Which is the correct YUV version？

### ISSUE THREAD

**Issue by JuZiSYJ** [RyanXingQL/SubjectiveQE-ESRGAN#1]
Hello, i notice that the png2yuv code in yours is
`    code = getattr(cv2, 'COLOR_BGR2YCrCb')
    ycrcb_img = cv2.cvtColor(bgr_img, code).astype(np.uint8)
    ycrcb_img[:h, :w, 0].tofile(fp)  # y
    ycrcb_img[:h, :w, 2].tofile(fp)  # cb (u)
    ycrcb_img[:h, :w, 1].tofile(fp)  # cr (v)`

However,the common use YUV in deblock like ARCNN is Matlab version. it is a little differetent with that in opencv
see https://github.com/hkchengrex/PyTorch-ARCNN/blob/master/loader.py

**Comment by ryanxingql** [comment]
Hi! Thanks for your comment!

I recently use this code for rgb2ycbcr conversion, which may address your concern:
https://github.com/RyanXingQL/PythonUtils/blob/2362aefe72e8f09b875c931bfda32ab43c0b63ae/conversion.py#L57-L78

This function will be used for my future programs. Thanks for your suggestion!
